version: "3.9"
services:
  server:
    image: node:22
    working_dir: /app
    command: sh -c "corepack enable && pnpm install && pnpm --filter @defuse/server dev"
    volumes:
      - ..:/app
    ports:
      - "3001:3001"
    env_file:
      - ../packages/server/.env

  client:
    image: node:22
    working_dir: /app
    command: sh -c "corepack enable && pnpm install && pnpm --filter @defuse/client dev -- --host 0.0.0.0"
    volumes:
      - ..:/app
    ports:
      - "5173:5173"
    env_file:
      - ../packages/client/.env
    depends_on:
      - server
